create table if not exists public.workouts (
  id bigint generated by default as identity primary key,
  professional text not null,
  objective text not null,
  condition text not null,
  duration text not null,
  location text not null,
  crefito text not null,
  published text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.physiotherapists (
  id bigint generated by default as identity primary key,
  user_id uuid unique references auth.users(id) on delete cascade,
  name text not null,
  crefito text not null,
  state text not null,
  specialty text not null,
  clinic text,
  phone text,
  rating numeric(2, 1) not null default 0,
  available boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.physiotherapists
add column if not exists user_id uuid unique references auth.users(id) on delete cascade;

alter table public.physiotherapists
add column if not exists clinic text;

alter table public.physiotherapists
add column if not exists phone text;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  physical_difficulty text not null,
  weekly_frequency text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
add column if not exists weekly_frequency text not null default '';

alter table public.workouts enable row level security;
alter table public.physiotherapists enable row level security;
alter table public.profiles enable row level security;

drop policy if exists "Allow public read workouts" on public.workouts;
drop policy if exists "Allow public read physiotherapists" on public.physiotherapists;
drop policy if exists "Users can read own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;

create policy "Allow public read workouts"
on public.workouts
for select
to anon, authenticated
using (true);

create policy "Allow public read physiotherapists"
on public.physiotherapists
for select
to anon, authenticated
using (true);

create policy "Users can read own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, physical_difficulty, weekly_frequency)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', ''),
    coalesce(new.raw_user_meta_data ->> 'physical_difficulty', ''),
    coalesce(new.raw_user_meta_data ->> 'weekly_frequency', '')
  )
  on conflict (id) do update
  set
    name = excluded.name,
    physical_difficulty = excluded.physical_difficulty,
    weekly_frequency = excluded.weekly_frequency,
    updated_at = now();

  if coalesce(new.raw_user_meta_data ->> 'role', '') = 'physiotherapist' then
    insert into public.physiotherapists (
      user_id,
      name,
      crefito,
      state,
      specialty,
      clinic,
      phone,
      rating,
      available
    )
    values (
      new.id,
      coalesce(new.raw_user_meta_data ->> 'name', ''),
      coalesce(new.raw_user_meta_data ->> 'crefito', ''),
      upper(coalesce(new.raw_user_meta_data ->> 'state', '')),
      coalesce(new.raw_user_meta_data ->> 'specialty', ''),
      nullif(new.raw_user_meta_data ->> 'clinic', ''),
      nullif(new.raw_user_meta_data ->> 'phone', ''),
      0,
      true
    )
    on conflict (user_id) do update
    set
      name = excluded.name,
      crefito = excluded.crefito,
      state = excluded.state,
      specialty = excluded.specialty,
      clinic = excluded.clinic,
      phone = excluded.phone;
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.workouts (
  professional,
  objective,
  condition,
  duration,
  location,
  crefito,
  published
)
select *
from (
  values
    ('Roberta', 'hipertrofia', 'Dor na lombar', '1h', 'Academia', 'CREFITO-5' || chr(10) || '123456-F', 'Publicado há 2 dias'),
    ('Juliana', 'Mobilidade', 'Mobilidade reduzida', '30min', 'Casa', 'CREFITO-5' || chr(10) || '123056-F', 'Publicado há 2 dias'),
    ('João', 'hipertrofia', 'Dor na lombar', '1h', 'Academia', 'CREFITO-5' || chr(10) || '123456-F', 'Publicado há 3 dias'),
    ('Roberta', 'Alongamento', 'Baixa mobilidade', '20min', 'Casa', 'CREFITO-5' || chr(10) || '123456-F', 'Publicado há 4 dias')
) as seed_workouts (
  professional,
  objective,
  condition,
  duration,
  location,
  crefito,
  published
)
where not exists (select 1 from public.workouts);

insert into public.physiotherapists (
  name,
  crefito,
  state,
  specialty,
  rating,
  available
)
select *
from (
  values
    ('Roberta da Silva', 'CREFITO-5 123456-F', 'RS', 'Dores na lombar', 4.5, true),
    ('Paula de Oliveira', 'CREFITO-5 123456-F', 'PR', 'Mobilidade reduzida', 4.8, true),
    ('Juliana Martins', 'CREFITO-5 123056-F', 'SC', 'Alongamento e mobilidade', 4.7, false),
    ('Marcos Pereira', 'CREFITO-5 654321-F', 'RS', 'Reabilitacao pos-cirurgica', 4.6, true)
) as seed_physiotherapists (
  name,
  crefito,
  state,
  specialty,
  rating,
  available
)
where not exists (select 1 from public.physiotherapists);
